.PHONY: all pdf diagrams svg clean distclean help

# Use the build script for all operations
SCRIPT = ../build.sh

all:
	@$(SCRIPT) all

pdf:
	@$(SCRIPT) pdf

diagrams:
	@$(SCRIPT) diagrams

svg:
	@$(SCRIPT) svg

clean:
	@$(SCRIPT) clean

distclean:
	@$(SCRIPT) distclean

help:
	@$(SCRIPT) help
